"""Human-in-the-loop approval node.

For the MVP, the HITL gate is an email digest:
- Top-N undigested jobs above the score floor are formatted as an HTML email
- The client gets one daily email with each match scored + reasoned
- Approve = apply to the role yourself via the link
- Reject = ignore; the job stays in the DB and won't be re-digested
  (idempotent via the digest_sent_at column)

Phase 2 adds: approve/reject links that fire a webhook, tailoring on approve,
auto-submit, etc.
"""
from __future__ import annotations

import os
import smtplib
import ssl
from datetime import datetime, timezone
from email.message import EmailMessage

from jinja2 import Template

from ..state import GraphState
from ..storage import db


HTML_TPL = Template("""\
<!doctype html>
<html><body style="font-family:-apple-system,Helvetica Neue,sans-serif;color:#0f172a;
                   background:#f8fafc;padding:24px;max-width:720px;margin:auto;">
  <h2 style="margin:0 0 4px;">Job matches for {{ date }}</h2>
  <p style="color:#64748b;margin:0 0 18px;">
    {{ jobs|length }} role(s) at or above your score floor.
    Click through to read and apply on your own schedule.
  </p>
  {% for j in jobs %}
  <div style="background:white;border:1px solid #e2e8f0;border-radius:8px;
              padding:14px 16px;margin-bottom:10px;">
    <div style="display:flex;justify-content:space-between;align-items:baseline;">
      <a href="{{ j.url }}" style="color:#0f172a;text-decoration:none;font-weight:600;
                                   font-size:15px;">{{ j.title }}</a>
      <span style="background:{{ '#16a34a' if j.score >= 80 else '#0891b2' if j.score >= 70 else '#6b7280' }};
                   color:white;font-size:12px;padding:2px 8px;border-radius:10px;">
        {{ j.score }}/100
      </span>
    </div>
    <div style="color:#475569;font-size:13px;margin-top:2px;">
      {{ j.company }}{% if j.location %} . {{ j.location }}{% endif %}
    </div>
    <div style="font-size:13px;margin-top:8px;color:#334155;">{{ j.reasoning }}</div>
    {% if j.strengths %}
    <div style="font-size:12px;margin-top:6px;color:#475569;">
      <strong>Fit:</strong> {{ j.strengths|join(", ") }}
    </div>
    {% endif %}
    {% if j.gaps %}
    <div style="font-size:12px;margin-top:2px;color:#9a3412;">
      <strong>Gaps:</strong> {{ j.gaps|join(", ") }}
    </div>
    {% endif %}
    <div style="margin-top:8px;">
      <a href="{{ j.url }}" style="color:#2563eb;font-size:13px;text-decoration:none;">
        Open posting,
      </a>
    </div>
  </div>
  {% endfor %}
  <p style="color:#94a3b8;font-size:12px;margin-top:18px;">
    Generated by your job-search agent. Reply to this email to adjust the scoring rubric.
  </p>
</body></html>
""")


def _send(html: str, subject: str) -> bool:
    host = os.environ.get("SMTP_HOST")
    port = int(os.environ.get("SMTP_PORT", "465"))
    user = os.environ.get("SMTP_USER")
    pw   = os.environ.get("SMTP_PASS")
    sender = os.environ.get("SMTP_FROM", user or "")
    to_addr = os.environ.get("DIGEST_TO")

    if not all([host, user, pw, to_addr]):
        print("  [approval] SMTP env vars missing, printing digest to stdout instead")
        print(html[:2000])
        return False

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = to_addr
    msg.set_content("Your email client does not support HTML.")
    msg.add_alternative(html, subtype="html")

    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP_SSL(host, port, context=ctx, timeout=30) as smtp:
            smtp.login(user, pw)
            smtp.send_message(msg)
        print(f"  [approval] digest sent to {to_addr}")
        return True
    except Exception as e:
        print(f"  [approval] send failed: {e}")
        return False


def approval_node(state: GraphState) -> GraphState:
    db_path = os.environ.get("DB_PATH", "./data/jobs.db")
    top_n = int(os.environ.get("DIGEST_TOP_N", "15"))
    min_score = int(os.environ.get("DIGEST_MIN_SCORE", "60"))

    db.init(db_path)
    scored = state.get("scored", [])
    if scored:
        inserted, updated = db.upsert_scored(db_path, scored)
        print(f"  [approval] db upsert: +{inserted} new, ~{updated} updated")

    pending = db.pending_for_digest(db_path, top_n=top_n, min_score=min_score)
    if not pending:
        print("  [approval] nothing new above score floor, no digest sent")
        return {"digest_sent": False}

    today = datetime.now(timezone.utc).strftime("%a %b %d")
    html = HTML_TPL.render(date=today, jobs=pending)
    sent = _send(html, subject=f"Job matches, {today} ({len(pending)})")
    if sent:
        db.mark_digested(db_path, [j["url"] for j in pending])

    return {"digest_sent": sent}
